# Generated by Django 2.2.6 on 2019-12-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191208_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='cancel',
            field=models.BooleanField(default=True),
        ),
    ]
