# Generated by Django 2.2.6 on 2019-11-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='note',
        ),
    ]
