# Generated by Django 2.2.6 on 2019-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customeruser_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
