# Generated by Django 2.2.6 on 2019-12-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20191213_1213'),
        ('user', '0005_auto_20191211_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='AuthUser',
        ),
    ]
