# Generated by Django 2.2.6 on 2019-12-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20191213_1213'),
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0006_auto_20191213_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUser',
            new_name='CustomerUser',
        ),
    ]
