# Generated by Django 2.2.6 on 2019-12-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20191213_1213'),
        ('user', '0008_auto_20191214_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomerUser',
        ),
    ]
