# Generated by Django 2.2.6 on 2019-12-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191214_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='address',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='name',
        ),
    ]
