# Generated by Django 2.2.6 on 2019-11-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=255)),
                ('type_parent', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('unit_price', models.IntegerField(default=0)),
                ('promotion_price', models.IntegerField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=0)),
                ('image', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TypeProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TypeProducts')),
            ],
        ),
    ]
