# Generated by Django 2.2.6 on 2020-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200205_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagess',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Ảnh sản phẩm Chính'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
