# Generated by Django 2.2.6 on 2020-02-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200205_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imagess',
            new_name='img',
        ),
    ]
