# Generated by Django 2.2.6 on 2020-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200205_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='Mã'),
        ),
    ]
