# Generated by Django 2.2.6 on 2020-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200205_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='CodeProduct',
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(default='', max_length=30, verbose_name='Mã'),
        ),
    ]
