# Generated by Django 2.2.6 on 2020-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200205_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
