# Generated by Django 2.2.6 on 2020-02-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200205_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='codeProduct',
            new_name='unit',
        ),
    ]
