# Generated by Django 2.2.6 on 2020-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200205_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
    ]
