# Generated by Django 2.2.6 on 2020-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200205_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Ảnh phụ'),
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Mã SP'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Ảnh sản phẩm Chính'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='products',
            name='new',
            field=models.BooleanField(default=0, verbose_name='Hàng mới'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion_price',
            field=models.IntegerField(default=0, verbose_name='Giá KM'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Giá SP'),
        ),
    ]
