# Generated by Django 2.2.6 on 2020-04-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200205_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='TypeProducts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TypeProducts', verbose_name='Loại sản phẩm'),
        ),
    ]
